# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:
  ghpage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Reconfigure git to use HTTP authentication
      run: >
           git config --global url."https://biswajitpain:${{ secrets.GH_TOKEN }}@github.com/biswajitpain/biswajitpain.github.io.git".insteadOf ssh://git@github.com/biswajitpain/biswajitpain.github.io.git \ 
           && git config --global user.email "email@biswajit.top" && git config --global user.name "Biswajit Pain" \
           && git remote set-url origin "https://biswajitpain:${{ secrets.GH_TOKEN }}@github.com/biswajitpain/biswajitpain.github.io.git"
      
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
      with:
        ruby-version: 2.6
    - name: Check files
      run:  pwd && ls -ltr
    - name: Run Install
      run: bundle install
    - name: Run GitHub
      run: rake github
