# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:
  ghpage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: true
    - name: Reconfigure git to use HTTP authentication
      run: >
           git config --global url."https://biswajitpain:${{ secrets.GITHUB_TOKEN }}@github.com/biswajitpain/biswajitpain.github.io".insteadOf ssh://git@github.com/biswajitpain/biswajitpain.github.io.git \ 
           && git config --global user.email "email@biswajit.top" && git config --global user.name "Biswajit Pain" \
           # && git remote set-url origin "https://${{ secrets.GITHUB_TOKEN }}@github.com/biswajitpain/biswajitpain.github.io"
      
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: 3.2
    - name: Check files
      run:  pwd && ls -ltr
    - name: Run Install
      run: bundle install
    - name: Run GitHub task
      env:
          GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      run: rake github
      
    - name: Create report file
      run: git push origin gh-pages
    
